### PR TITLE
Update classes following the current draft

### PR DESCRIPTION
**Pull request by yuripourre**
This is an attempt to update the classes to reflect the current state of the WebXR draft. This is the farthest I could get.

It is almost working (manually tested using console + WebXR emulator) the only problem so far is: When I try to call `xrSession.requestAnimationFrame((time,frame)->myMethod(time,frame)` it simply doesn't work.

Can you help me? @treblereel

### CODE REVIEW

**Comment by treblereel** [comment]
@yuripourre 

Hello, i think, it's very outdated, i merged all my elemental2-like stuff here : https://github.com/treblereel/elemental2-experimental/tree/main/java/org/treblereel/gwt/elemental2

If you need, i can publish it to maven repos

In case you want to discuss elemental2 topics, join our gitter channel : https://gitter.im/vertispan/j2cl

**Comment by yuripourre** [comment]
@treblereel thank you so much for the reply.

Whoa! The WebXR code seems updated, do you have any working example?

I will try to generate the java classes from your repo and then try to port some examples that I have. Thanks for the offer, if I have trouble generating the classes, I will kindly ask you to publish them if it's not too much work for you.

**Comment by treblereel** [comment]
@yuripourre np, it's easy, i can generete new java wrappers from latest closure extensions in a seconds, so let me know your results.

by the way, are you running gwt2 or j2cl ? if gwt2, there is existing j2cl-maven-plugin you can use.

PS : Right now i am working on generating three.js elemental2-like wrappers;

**Comment by yuripourre** [comment]
@treblereel okay, if it's not a burden I would appreciate a lot the java wrappers.

I am currently trying to make libGDX works with WebXR and it uses GWT2.

I've never heard about j2cl until I found your repos. How is the progress with three.js so far?

**Comment by yuripourre** [comment]
@treblereel I downloaded and moved bazel 3.3.0 to /usr/bin but when I try to run `sh build.sh` I got errors, maybe I am missing something (I am not sure how to build bazel projects):
```
Dec 03, 2021 11:49:11 AM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 9 error(s), 8 warning(s)
Dec 03, 2021 11:49:11 AM jsinterop.generator.helper.Problems report
SEVERE: Javascript compilation error: Bad type annotation. Unknown type FileSystemEntry
Dec 03, 2021 11:49:11 AM jsinterop.generator.helper.Problems report
SEVERE: Javascript compilation error: Bad type annotation. Unknown type FileSystemDirectoryEntry
Dec 03, 2021 11:49:11 AM jsinterop.generator.helper.Problems report
SEVERE: Javascript compilation error: Bad type annotation. Unknown type FileSystemDirectoryReader
Dec 03, 2021 11:49:11 AM jsinterop.generator.helper.Problems report
SEVERE: Javascript compilation error: Bad type annotation. Unknown type FileSystemFileEntry
Dec 03, 2021 11:49:11 AM jsinterop.generator.helper.Problems report
SEVERE: Javascript compilation error: Bad type annotation. Unknown type FileSystem
Dec 03, 2021 11:49:11 AM jsinterop.generator.helper.Problems report
SEVERE: Javascript compilation error: Bad type annotation. Unknown type FileSystem
Dec 03, 2021 11:49:11 AM jsinterop.generator.helper.Problems report
SEVERE: Javascript compilation error: Bad type annotation. Unknown type FileSystem
Dec 03, 2021 11:49:11 AM jsinterop.generator.helper.Problems report
SEVERE: Javascript compilation error: Bad type annotation. Unknown type FileSystem
Dec 03, 2021 11:49:11 AM jsinterop.generator.helper.Problems report
SEVERE: Javascript compilation error: Bad type annotation. Unknown type FileSystem
Dec 03, 2021 11:49:11 AM jsinterop.generator.helper.Problems report
INFO: 0 notice(s), 0 warning(s), 9 error(s)
Target //java/org/treblereel/gwt/elemental2/filesystem:libfilesystem-src.jar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.516s, Critical Path: 2.35s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by yuripourre** [comment]
@treblereel thank you so much for updating [elemental2-experimental](https://github.com/treblereel/elemental2-experimental/) now it builds! I will do some experiments later today.

**Comment by treblereel** [comment]
@yuripourre welcome! i am going to close this repo as updated, so let's move to gitter/google chat if possible

**Comment by yuripourre** [comment]
@treblereel sure!

**Pull request closed without merging**
